# Generated by Django 5.1.4 on 2026-09-22 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200, verbose_name='封存原因')),
                ('archived_by', models.CharField(max_length=64, verbose_name='封存操作者')),
                ('archived_at', models.DateTimeField(auto_now_add=True, verbose_name='封存时刻')),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archive_record', to='inspection.inspection', verbose_name='巡检记录')),
            ],
            options={
                'ordering': ['-archived_at'],
            },
        ),
    ]
